provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1

package:
  individually: true
  exclude:
    - coverage/**
    - .circleci/**

custom:
  stagename: $(opt:stage, 'prod')

service: test-endpoint

functions:
  - ${file(./handlers/projects/projects.yml)}
  - ${file(./handlers/users/users.yml)}