version: 1
jobs:
  build:
    working_directory: ~/community-portal

    docker:
      - image: circleci/node:10.3

    steps:
      - checkout
      - run:
          name: Setup environmental variables
          environment: 
            STAGE: "dev"

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "./functions/package.json" }}
            - dependencies-cachep

      - run:
          name: Install dependencies
          command: |
            sudo npm i -g serverless
            cd functions
            npm install
        
      - run:
          name: run tests
          command: |
            cd functions
            npm test

      - run:
          name: deploy application
          command: |
            cd functions
            sls deploy --stage $STAGE
          
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "./functions/package.json" }}

