version: 1
jobs:
  build:
    working_directory: ~/community-portal
    environment: 
      STAGE: "staging"

    docker:
      - image: circleci/node:10.3

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "./functions/package.json" }}
            - dependencies-cachep

      - run:
          name: Install dependencies
          command: |
            sudo npm i -g serverless
            cd functions
            npm install
        
      - run:
          name: run tests
          command: |
            cd functions
            npm test
            
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "./functions/package.json" }}

          
  deploy:
    working_directory: ~/community-portal/functions

    docker:
      - image: circleci/node:10.3

    steps:
      - checkout:
          path: ~/community-portal
      - run:
          name: deploy application
          command: |
            npm install 
            echo ${CIRCLE_BRANCH}
            sls deploy --stage $STAGE

workflows:
  version: 1
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
         